name: "Location"
main: "org.xiaomu.Location.Location"
author: "xiaomu18"
website: "https://github.com/xiaomu18/"
version: "1.0.4"
api-version: "1.16"
softdepend: [ PlaceholderAPI ]
description: "一个支持查看玩家真实地理位置定位和运营商信息的插件"

commands:
  Location: # 命令的基本名，请不要使用奇怪的字符！
    aliases: # 别名，方便玩家使用
      - "lc"
    usage: "/Location help 获取命令帮助." # 用法
    description: "显示对某玩家的地理定位信息和网络运营商信息" # 描述
    permission: "minecraft.command.Location" # 需要的权限，通常不用
    permission-message: "你没有管理员权限！" # 无权限返回的消息，通常不用